name: Windows

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      # explicit include-based build matrix, of known valid options
      matrix:
        include:
          - os: windows-2019
            visual_studio: "Visual Studio 16 2019"
    env:
      build_dir: "build"
      config: "Release"

    steps:
      - uses: actions/checkout@v2

      - name: python --version.
        run: |
          which python
          python --version

      - name: python3 --version.
        run: |
          which python3
          python3 --version


      - name: absolute path to python --version.
        run: |
          C:/hostedtoolcache/windows/Python/3.9.1/x64/python.exe --version

      - name: absolute path to python3 --version.
        run: |
          C:/hostedtoolcache/windows/Python/3.9.1/x64/python3.exe --version


      - name: create venv with python
        run: |
          python -m venv py-env
          ls py-env

      - name: create venv with python3
        run: |
          python3 -m venv --symlinks py3-env 
          ls py3-env

      # - name: python3 version.
      #   run: |
      #     C:/hostedtoolcache/windows/Python/3.9.1/x64/python.exe --version

      # ls -al C:/hostedtoolcache/windows/Python/3.9.1/x64/

      - name: Find all python3.exe
        run: find /c/hostedtoolcache/windows/Python -type f -name "python3.exe"
        shell: bash

      # On windows, use -DPython_Executable to try and get it to use python.exe not python3.exe
      - name: Configure CMake
        id: configure
        run: cmake . -B ${{ env.build_dir }} -G "${{ matrix.visual_studio }}" -A x64 -DPython_Executable=$(which python)
        shell: bash


      # - name: Build
      #   run: cmake --build . --config ${{ env.config }} --target all --verbose
      #   working-directory: ${{ env.build_dir }}